var TopLevel = {
"add" : function () {},
"addEventListener" : function () {},
"BackSide" : function () {},
"bindKey" : function () {},
"body" : function () {},
"charCodeAt" : function () {},
"document" : function () {},
"DoubleSide" : function () {},
"FullScreen" : function () {},
"getElementById" : function () {},
"getObject" : function () {},
"HemisphereLight" : function () {},
"innerHeight" : function () {},
"innerWidth" : function () {},
"material.color.set" : function () {},
"Mesh" : function () {},
"mesh" : function () {},
"MeshBasicMaterial" : function () {},
"position.set" : function () {},
"requestPointerLock" : function () {},
"Sphere" : function () {},
"SphereGeometry" : function () {},
"THREE" : function () {},
"THREEx" : function () {},
"window" : function () {},
"WindowResize" : function () {}
}
